server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_ie?characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password

mybatis:
  type-aliases-package: io.github.cocodx.entity
  mapper-locations: classpath:mybatis/mapper/*.xml

minio:
  endPoint: http://localhost:9000
  accessKey: minioadmin
  secretKey: minioadmin
